---
- name: gocd_agent | installing go-agent
  apt:
    name: "go-agent"
    state: present

- name: gocd_agent | configuring go-agent
  template:
    src: "etc/default/go-agent.j2"
    dest: "/etc/default/go-agent"
    owner: go
    group: go
    mode: 0644
  notify:
    - restart go-agent

- name: gocd_agent | ensuring go-agent is running
  service:
    name: "go-agent"
    state: started
